services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      allow-flight: "TRUE"
      DIFFICULTY: "peaceful"
      MODE: "creative"
      GAMEMODE: "creative"
    restart: always
    ports:
      - "19132:19132/udp"
    volumes:
      - /files-nas20/files/minecraft/bedrock/data:/data
    stdin_open: true
    tty: true