services:
  bds:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
    ports:
      - "19132:19132/udp"
    volumes:
      - /files-nas20/files/minecraft/bedrock/data:/data
    stdin_open: true
    tty: true