version: "3.8"

services:
  bds:
    image: itzg/minecraft-bedrock-server
    container_name: bds_mods
    environment:
      EULA: "TRUE"
      GAMEMODE: "creative"        # Bedrock-compatible
      DIFFICULTY: "peaceful"      # Bedrock-compatible
      allow-flight: "true"
      ENABLE_CHEATS: "true"
      OPS: "979dcf0297df3ab7"
      ENABLE_SSH: "TRUE"
    ports:
      - "19142:19132/udp"
      - "2222:2222"
    expose:
      - 2222
    volumes:
      - /files-nas20/files/minecraft/bedrock_mods/data:/data
    restart: always
    stdin_open: true
    tty: true

  backup:
    image: kaiede/minecraft-bedrock-backup
    container_name: backup_mods
    restart: always
    depends_on:
      - "bds"
    environment:
      TZ: "America/Chicago"
    volumes:
      # Backup config (YAML, schedules, etc.)
      - /files-nas20/files/minecraft/backups/bedrock_mods/config:/config
      - /files-nas20/files/minecraft/backups/bedrock_mods/backup:/data
