services:
  bds:
    image: itzg/minecraft-bedrock-server
    container_name: bds_modded
    environment:
      EULA: "TRUE"
      GAMEMODE: "creative"        # correct for Bedrock
      DIFFICULTY: "peaceful"      # also valid for Bedrock
      allow-flight: "true"
      ENABLE_CHEATS: "true"
      OPS: "979dcf0297df3ab7" 
    ports:
      - "19132:19132/udp"
    volumes:
      - /files-nas20/files/minecraft/bedrock_modded/data:/data
    restart: always
    stdin_open: true
    tty: true
