services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "19192:19132/udp"
    environment:
      EULA: "TRUE"
      allow-flight: "TRUE"
      DIFFICULTY: "peaceful"
      MODE: "creative"
      GAMEMODE: "creative"
      ENABLE_RCON: "false"
      OPS: "dbb3f9a2-f031-409a-9449-77707eff0095,00000000-0000-0000-0009-000001aa66ec"
      ENABLE_CHEATS: "true"
      TYPE: "PAPER"
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
      CF_API_KEY: '\$2a\$10\$yIonByij6xedZr7UFKcbWO33r8dmKiepz0MZv.jNJkmYv3rtlEuXy'
      CURSEFORGE_FILES: |
        luckytnt       

    restart: always
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - /files-nas20/files/minecraft/java/data:/data