containers:
  bedrock:
    - name: bds_mods
      ssh: bds_mods:2222
      passwordFile: /files-nas20/files/minecraft/bedrock_mods/.remote-console.yaml
      worlds:
        - "/data/worlds/bedrock_level"

trim:
  trimDays: 4
  keepDays: 28
  minKeep: 2

schedule:
  interval: 3h
