services:
  bds:
    image: itzg/minecraft-bedrock-server
    container_name: bds_lotr
    environment:
      EULA: "TRUE"
      GAMEMODE: "creative"        # Bedrock-compatible
      DIFFICULTY: "peaceful"      # Bedrock-compatible
      allow-flight: "true"
      ENABLE_CHEATS: "true"
      ENABLE_SSH: "TRUE"
      ALLOW_LIST_USERS: "ridingintraffic:979dcf0297df3ab7,claracorn4105:87b61eab4e67a2f6,lukey2894:6dd23a63ddd61554"
      EXISTING_OPS_FILE: "SYNCHRONIZE"
      OPS: "979dcf0297df3ab7,87b61eab4e67a2f6,6dd23a63ddd61554,2533274818340588,2535440271788039,2535471962177604"
    ports:
      - "19162:19132/udp"
      - "2222:2222"
    expose:
      - 2222
    volumes:
      - /files-nas20/files/minecraft/bedrock_lotr/data:/data
    restart: always
    stdin_open: true
    tty: true
